spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://**.**.**.**:3306/username
    username: username
    password: password

server:
  port: 7529
  servlet:
    context-path: /api
#    session:
#      cookie:
#        domain: www.**.com
  address: 0.0.0.0
