spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.43.234.93:3306/langoapi
    username: langoapi
    password: WZtY3xbt6tmDf2Dn

server:
  port: 7529
  servlet:
    context-path: /api
#    session:
#      cookie:
#        domain: lg-sp.cn
  address: 0.0.0.0